version: "3.8"
services: 
  queue:
    build: ./Queue/
    container_name: queue
    image: "queue:latest"
    networks:
      - web_net
    depends_on: 
      - redis
    volumes: 
      - ${PWD}/files:/workspace/files/
  redis:
    build: ./Redis/
    container_name: redis
    image: "redis:latest"
    networks:
      - web_net
    ports: 
      - "6379:6379"
networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local
