version: "3.8"
services: 
  back-end:
    build: ./BackEnd/
    container_name: backend
    image: "flask_base:latest"
    networks:
      - web_net
    ports:
     - "5000:5000"
    depends_on: 
      - db
    volumes: 
      - ${PWD}/files:/workspace/files/
  db: 
    build: ./Database/
    container_name: database
    image: "postgres_base:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local
