version: "3.8"
services: 
  db: 
    build: ./Database/
    container_name: database
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local
