version: "3.8"
services: 
  back-end:
    build: ./BackEnd/
    container_name: backend
    image: "flask_base:latest"
    networks:
      web_net:
        ipv4_address: 10.80.1.3
  nginx:
    build: ./Nginx/
    container_name: nginx
    image: "nginx:latest"
    networks:
      web_net:
        ipv4_address: 10.80.1.2
    depends_on: 
      - back-end
    ports: 
      - "8080:8080"
    volumes: 
      - ${PWD}/Nginx:/etc/nginx/conf.d
networks:
    web_net:
        driver: bridge
        ipam:
         config:
           - subnet: 10.80.1.0/28
             gateway: 10.80.1.1

volumes: 
  pg-data: 
    driver: local
