version: "3.8"
services: 
  back-end:
    build: ./BackEnd/
    container_name: backend
    image: "flask_base:latest"
    networks:
      - web_net
    ports:
     - "5000:5000"
    volumes: 
      - ${PWD}/files:/workspace/files/
  nginx:
    build: ./Nginx/
    container_name: nginx
    image: "nginx:latest"
    networks:
      - web_net
    depends_on: 
      - back-end
    ports: 
      - "8080:8080"
    volumes: 
      - ${PWD}/Nginx:/etc/nginx/conf.d
networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local
